
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mucadegwpdrpnagmmirj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11Y2FkZWd3cGRycG5hZ21taXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDE4NjQsImV4cCI6MjA2NDk3Nzg2NH0.zs3DNtic1gYcHiAa9zoX3hP8LdGNoRLepFrAxjRjFlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window?.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: `sb-${SUPABASE_URL.split('//')[1].split('.')[0]}-auth-token`,
    flowType: 'pkce'
  }
});
